import type { RawProduct } from "@/types/product";

export const fallbackProducts: RawProduct[] = [
  {
    id: 1,
    title: "Brushed Rattan Crate",
    brand: "Orla & Vine",
    category: "Storage",
    tags: ["brushed", "crate", "rattan"],
    price: 1111.05,
    rating: 3.4,
    reviews: 176,
    inStock: true,
    releasedAt: "2022-02-18",
    image: "https://picsum.photos/seed/cat1/500/320",
    imageWidth: 500,
    imageHeight: 320,
    description: "Small-batch Rattan crate, made to order."
  },
  {
    id: 2,
    title: "Minimal Linen Planter Box",
    brand: "Sol & Stone",
    category: "Outdoor",
    tags: ["box", "linen", "minimal"],
    price: 1031.44,
    rating: 4.1,
    reviews: 1396,
    inStock: true,
    releasedAt: "2025-11-07",
    image: "https://picsum.photos/seed/cat2/300/400",
    imageWidth: 300,
    imageHeight: 400,
    description: "Small-batch Linen planter box, made to order."
  },
  {
    id: 3,
    title: "Sculptural Terracotta Tumbler",
    brand: "Fenwick",
    category: "Bath",
    tags: ["sculptural", "terracotta", "tumbler"],
    price: 478.77,
    rating: 4.6,
    reviews: 167,
    inStock: true,
    releasedAt: "2024-06-24",
    image: "https://picsum.photos/seed/cat3/360/480",
    imageWidth: 360,
    imageHeight: 480,
    description: "Our best-selling tumbler, now in Terracotta."
  },
  {
    id: 4,
    title: "Minimal Rattan Cutting Board",
    brand: "Orla & Vine",
    category: "Kitchen",
    tags: ["kitchen", "minimal"],
    price: 1501.18,
    rating: 3.7,
    reviews: 717,
    inStock: true,
    releasedAt: "2024-02-27",
    image: "https://picsum.photos/seed/cat4/360/480",
    imageWidth: 360,
    imageHeight: 480,
    description: "A Minimal Rattan cutting board for everyday use."
  },
  {
    id: 5,
    title: "Wide Leather Tea Towel",
    brand: "Otto Lane",
    category: "Textiles",
    tags: ["leather", "textiles", "towel", "wide"],
    price: 665.19,
    rating: 3.7,
    reviews: 1251,
    inStock: true,
    releasedAt: "2022-05-05",
    image: "https://picsum.photos/seed/cat5/400/300",
    imageWidth: 400,
    imageHeight: 300,
    description: "Our best-selling tea towel, now in Leather."
  },
  {
    id: 6,
    title: "Stackable Velvet Cutting Board",
    brand: "Briar Goods",
    category: "Kitchen",
    tags: ["board", "kitchen", "stackable", "velvet"],
    price: 1681.01,
    rating: 3.3,
    reviews: 360,
    inStock: true,
    releasedAt: "2022-01-16",
    image: "https://picsum.photos/seed/cat6/300/400",
    imageWidth: 300,
    imageHeight: 400,
    description: "Small-batch Velvet cutting board, made to order."
  }
];
